import {connect} from '../../../../tools/tpt-work/automation/session.mjs';
import {connectSkills} from '../../../../tools/tpt-work/automation/skills.mjs';
export async function openAtProbe(ctx){const c=await connect(ctx);try{const act=await ctx.recorder.action('观察实际引用菜单','fill','@',async()=>{await c.page.locator('[data-composer-input]').fill('@');await c.page.waitForTimeout(600);});const read=await ctx.recorder.read('引用菜单现场','reference-menu-dom',{channel:'dom',scope:'composer引用菜单'},async()=>({value:await c.page.evaluate(()=>({text:document.body.innerText.slice(-4500),popups:[...document.querySelectorAll('[role="listbox"],[role="menu"],[data-composer-menu]')].filter(e=>e.getClientRects().length).map(e=>({text:e.innerText,html:e.outerHTML}))}))}));return {action_refs:[act.event_id],observations:{read}};}finally{await c.close();}}
export async function inspectTree(ctx){const c=await connectSkills(ctx,{preserveView:true});try{const read=await ctx.recorder.read('目录树实际展开属性','skill-tree-dom',{channel:'dom',scope:'当前技能详情目录树'},async()=>({value:await c.frame.locator('[class*="dir-tree"]').evaluate(el=>({html:el.outerHTML,text:el.innerText}))}));return {observations:{read}};}finally{await c.close();}}
import {readDraftState,removeAttachment} from '../../../../tools/tpt-work/business/attachments/manage.mjs';
import {searchSkills,setSkillEnabled} from '../../../../tools/tpt-work/business/skills/manage.mjs';
import fs from 'node:fs';
export async function disableOwnedFixtures(ctx){const registry=JSON.parse(fs.readFileSync(ctx.environment.skills_registry,'utf8'));const names=Object.keys(registry.entries).filter(n=>/audit(?:2)?-20261007/.test(n)||n==='missing-name');const rows=[];for(const name of names){try{const searched=await searchSkills({...ctx,internalName:undefined},{term:name});const titles=searched.observations.count.raw.titles;if(titles.length!==1)throw Error('Owned fixture search not unique: '+name);const r=await setSkillEnabled({...ctx,internalName:name},{displayName:titles[0],value:false,internalName:name});rows.push({name,before:r.observations.before?.value,after:r.observations.after?.value,events:r});}catch(e){rows.push({name,error:e.message});}}const read=await ctx.recorder.read('本轮新增技能停用结果','owned-fixtures-cleanup',{channel:'dom+file',scope:'仅本验收run与已确认新增missing-name'},async()=>({value:rows,raw:{names,rows}}));return {observations:{read}};}
export async function linkControl(ctx,args){const read=await ctx.recorder.read('本轮链接服务存活正对照',args.url,{channel:'http',scope:'仅回环本轮夹具'},async()=>{const u=new URL(args.url);if(u.hostname!=='127.0.0.1')throw Error('Loopback fixture required');const r=await fetch(u,{signal:AbortSignal.timeout(3000)}),text=await r.text();return {value:r.ok&&text.includes('FAST_LINK_TARGET '+args.run),raw:{status:r.status,text,url:args.url}};});return {observations:{read}};}
export async function focusedShortcut(ctx){const c=await connect(ctx);try{const before=await ctx.recorder.read('快捷键前焦点','focus',{channel:'dom',scope:'主窗口'},async()=>({value:await c.page.evaluate(()=>({focused:document.hasFocus(),active:document.activeElement.outerHTML.slice(0,500)}))}));const act=await ctx.recorder.action('激活主窗口并触发搜索快捷键','focus-and-press',null,async()=>{await c.page.bringToFront();await c.page.locator('body').click({position:{x:2,y:2}});await c.page.keyboard.press('Control+K');await c.page.waitForTimeout(600);});const read=await ctx.recorder.read('激活后搜索面板与焦点','search-focus',{channel:'dom',scope:'主窗口搜索弹窗'},async()=>{const raw=await c.page.evaluate(()=>({focused:document.hasFocus(),active:document.activeElement.outerHTML.slice(0,500),panel:!!document.querySelector('[data-tpt-search-dialog]'),input:document.querySelector('[data-tpt-search-input]')?.outerHTML}));return {value:raw.panel,raw};});await c.page.keyboard.press('Escape');return {action_refs:[act.event_id],observations:{before,read}};}finally{await c.close();}}
export async function closeFrameDialogs(ctx){const c=await connect(ctx);try{const action=await ctx.recorder.action('关闭验收遗留的页面内导入弹窗','click-close',null,async()=>{for(const f of c.page.frames()){const ds=f.locator('[role="dialog"]');for(const d of await ds.all()){if(!await d.isVisible())continue;const cancel=d.getByRole('button',{name:'取消',exact:true});const cross=d.locator('button').filter({hasText:/^×$/});if(await cancel.count())await cancel.click();else if(await cross.count())await cross.click();else await f.locator('body').press('Escape');}}});return {action_refs:[action.event_id],...(await inspectSurface({...ctx,connection:c}))};}finally{await c.close();}}
export async function clearAttachments(ctx){const c=await connect(ctx);try{const state=await readDraftState({...ctx,connection:c});const names=state.observations.names.value;const actions=[];for(const name of names){const r=await removeAttachment({...ctx,connection:c},{name});actions.push(...r.action_refs);}const after=await readDraftState({...ctx,connection:c});if(after.observations.count.value!==0)throw Error('Draft cleanup incomplete');return {action_refs:actions,observations:{before:state.observations.names,after:after.observations.names}};}finally{await c.close();}}
export async function inspectSurface(ctx){const c=await connect(ctx);try{const read=await ctx.recorder.read('验收现场可见控件与DOM','audit-surface',{channel:'dom',scope:'主界面及iframe'},async()=>{const frames=[];for(const f of c.page.frames()){if(f.url()==='about:blank')continue;if(f!==c.page.mainFrame()){const el=await f.frameElement();if(!await el.isVisible())continue;}frames.push(await f.evaluate(()=>{const visible=e=>!!(e.offsetWidth||e.offsetHeight||e.getClientRects().length);return {url:location.href,text:document.body.innerText.slice(-14000),inputs:[...document.querySelectorAll('input,textarea,[contenteditable="true"]')].filter(visible).map(e=>({outer:e.outerHTML.slice(0,1400),value:e.value??e.innerText})),buttons:[...document.querySelectorAll('button')].filter(visible).map(e=>({text:e.innerText,aria:e.getAttribute('aria-label'),outer:e.outerHTML.slice(0,400)})),dialogs:[...document.querySelectorAll('[role="dialog"],[data-shortcut-modal]')].filter(visible).map(e=>({outer:e.outerHTML.slice(0,3000)}))};}));}return {value:frames,raw:{frames}};});return {observations:{read}};}finally{await c.close();}}
