import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
const library=path.resolve(fileURLToPath(new URL('../../',import.meta.url)));
const sha=data=>crypto.createHash('sha256').update(data).digest('hex');
export async function prepareFixtures(ctx,args){
 const script=path.join(library,'maintenance/prepare-fixtures.py');let stdout='',stderr='';
 const action=await ctx.recorder.action('创建本轮唯一样本','python',{run:args.run},async()=>{await new Promise((resolve,reject)=>{const child=spawn(ctx.environment.python||'python',['-X','utf8',script,'--run',args.run,'--task-root',ctx.taskRoot],{windowsHide:true});child.stdout.on('data',d=>stdout+=d);child.stderr.on('data',d=>stderr+=d);child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(Error(stderr||'Fixture process failed '+code)));});});
 const result=JSON.parse(stdout.trim());const read=await ctx.recorder.read('夹具生成结果','fixtures:'+args.run,{channel:'file',scope:result.fixture_root},async()=>({value:result,raw:{stdout}}));return {action_refs:[action.event_id],observations:{read}};
}
export async function backupFile(ctx,args){const p=path.resolve(args.path),data=fs.readFileSync(p),digest=sha(data),dest=path.join(ctx.taskRoot,'恢复备份',digest+'.bin');fs.mkdirSync(path.dirname(dest),{recursive:true});if(!fs.existsSync(dest))fs.writeFileSync(dest,data);
 const read=await ctx.recorder.read('原文件备份',p,{channel:'file',scope:'本轮恢复备份'},async()=>({value:{path:p,backup:dest,sha256:digest},raw:{bytes:data.length}}));return {observations:{read}};}
export async function writeFile(ctx,args){const p=path.resolve(args.path);const action=await ctx.recorder.action('写入本轮夹具文件','writeFile',{path:p},async()=>{if(args.expectedHash&&sha(fs.readFileSync(p))!==args.expectedHash)throw Error('Original file changed before write');fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,args.content,'utf8');});return {action_refs:[action.event_id],...(await readFile(ctx,{path:p}))};}
export async function readFile(ctx,args){const p=path.resolve(args.path);const read=await ctx.recorder.read('本轮文件真实内容及哈希',p,{channel:'file',scope:p},async()=>{if(!fs.existsSync(p))return {value:null,raw:{exists:false,path:p}};const data=fs.readFileSync(p);return {value:{text:data.toString('utf8'),sha256:sha(data),bytes:data.length},raw:{exists:true,path:p}};});return {observations:{read}};}
export async function restoreFile(ctx,args){const b=path.resolve(args.backup);if(!b.startsWith(path.join(ctx.taskRoot,'恢复备份')+path.sep))throw Error('Backup must belong to this task');const data=fs.readFileSync(b);if(sha(data)!==args.sha256)throw Error('Backup hash mismatch');const action=await ctx.recorder.action('按备份恢复原文件','restoreFile',{path:args.path},async()=>{fs.writeFileSync(args.path,data);});const result=await readFile(ctx,{path:args.path});if(result.observations.read.value.sha256!==args.sha256)throw Error('Restored hash mismatch');return {action_refs:[action.event_id],...result};}
export async function prepareProjectFiles(ctx,args){
 const base=path.resolve(args.projectRoot,'.tpt-tool-'+args.run);if(fs.existsSync(base))throw Error('Project fixture directory exists; reuse or select a fresh run');
 const files={'flow.txt':'FAST_FLOW_INPUT','long.txt':Array.from({length:200},(_,i)=>'FAST_LONG_LINE_'+String(i+1).padStart(3,'0')).join('\n'),'code-on.js':'module.exports = 0;','code-off.js':'module.exports = 0;'};
 const action=await ctx.recorder.action('准备读写/长输出场景','create-files',{base},async()=>{fs.mkdirSync(base,{recursive:true});for(const [name,text]of Object.entries(files))fs.writeFileSync(path.join(base,name),text);});const read=await ctx.recorder.read('项目夹具实际文件',base,{channel:'file',scope:base},async()=>({value:{base,files:Object.keys(files).map(name=>({path:path.join(base,name),sha256:sha(fs.readFileSync(path.join(base,name)))})),deliveryPath:path.join(base,'deliver.txt')},raw:{base}}));return {action_refs:[action.event_id],observations:{read}};
}
export async function identityDelta(ctx,args){const before=[...new Set(args.before)].sort(),after=[...new Set(args.after)].sort();const read=await ctx.recorder.read('内部身份集合增量','identity-delta',{channel:'derived',scope:'本轮注册表前后读值',event_refs:args.readRefs||[]},async()=>({value:{added:after.filter(x=>!before.includes(x)),removed:before.filter(x=>!after.includes(x)),unchanged:JSON.stringify(before)===JSON.stringify(after)},raw:{before,after}}));return {observations:{read}};}
