import {connect} from '../../automation/session.mjs';
import * as navigation from '../../automation/pc88/session.mjs';
import * as conversation from '../../automation/pc88/conversation.mjs';
import * as skills from '../../automation/pc88/skills.mjs';
export async function navigation_skillsFrame(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 navigation.skillsFrame','navigation.skillsFrame',{channel:'dom',scope:'navigation'},async()=>{const result=await navigation.skillsFrame(c.page);return {value:result?{url:result.url()}:null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function navigation_expertsFrame(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 navigation.expertsFrame','navigation.expertsFrame',{channel:'dom',scope:'navigation'},async()=>{const result=await navigation.expertsFrame(c.page);return {value:result?{url:result.url()}:null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function navigation_closeDialogs(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 navigation.closeDialogs','navigation.closeDialogs',{channel:'dom',scope:'navigation'},async()=>{const result=await navigation.closeDialogs(c.page, args.tries);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function navigation_ensureMoreMenu(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 navigation.ensureMoreMenu','navigation.ensureMoreMenu',{channel:'dom',scope:'navigation'},async()=>{const result=await navigation.ensureMoreMenu(c.page);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function navigation_goHome(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 navigation.goHome','navigation.goHome',{channel:'dom',scope:'navigation'},async()=>{const result=await navigation.goHome(c.page);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function navigation_openSkills(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 navigation.openSkills','navigation.openSkills',{channel:'dom',scope:'navigation'},async()=>{const result=await navigation.openSkills(c.page);return {value:result?{url:result.url()}:null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function navigation_openExperts(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 navigation.openExperts','navigation.openExperts',{channel:'dom',scope:'navigation'},async()=>{const result=await navigation.openExperts(c.page);return {value:result?{url:result.url()}:null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function navigation_closeSidebarPanels(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 navigation.closeSidebarPanels','navigation.closeSidebarPanels',{channel:'dom',scope:'navigation'},async()=>{const result=await navigation.closeSidebarPanels(c.page);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function conversation_readComposerState(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 conversation.readComposerState','conversation.readComposerState',{channel:'dom',scope:'conversation'},async()=>{const result=await conversation.readComposerState(c.page);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function conversation_selectProject(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 conversation.selectProject','conversation.selectProject',{channel:'dom',scope:'conversation'},async()=>{const result=await conversation.selectProject(c.page, args.name);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function conversation_setReasoning(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 conversation.setReasoning','conversation.setReasoning',{channel:'dom',scope:'conversation'},async()=>{const result=await conversation.setReasoning(c.page, args.level);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function conversation_typeDraft(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 conversation.typeDraft','conversation.typeDraft',{channel:'dom',scope:'conversation'},async()=>{const result=await conversation.typeDraft(c.page, args.text);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function conversation_send(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 conversation.send','conversation.send',{channel:'dom',scope:'conversation'},async()=>{const result=await conversation.send(c.page);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function conversation_waitForIdle(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 conversation.waitForIdle','conversation.waitForIdle',{channel:'dom',scope:'conversation'},async()=>{const result=await conversation.waitForIdle(c.page, args.timeoutMs);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function conversation_readAssistantMessages(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 conversation.readAssistantMessages','conversation.readAssistantMessages',{channel:'dom',scope:'conversation'},async()=>{const result=await conversation.readAssistantMessages(c.page);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function conversation_isCompleted(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 conversation.isCompleted','conversation.isCompleted',{channel:'dom',scope:'conversation'},async()=>{const result=await conversation.isCompleted(c.page);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function skills_skillsFrame(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 skills.skillsFrame','skills.skillsFrame',{channel:'dom',scope:'skills'},async()=>{const result=await skills.skillsFrame(c.page);return {value:result?{url:result.url()}:null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function skills_ensureMenu(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 skills.ensureMenu','skills.ensureMenu',{channel:'dom',scope:'skills'},async()=>{const result=await skills.ensureMenu(c.page);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function skills_openSkills(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 skills.openSkills','skills.openSkills',{channel:'dom',scope:'skills'},async()=>{const result=await skills.openSkills(c.page);return {value:result?{url:result.url()}:null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function skills_closeSkills(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 skills.closeSkills','skills.closeSkills',{channel:'dom',scope:'skills'},async()=>{const result=await skills.closeSkills(c.page);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function skills_importSkill(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 skills.importSkill','skills.importSkill',{channel:'dom',scope:'skills'},async()=>{const result=await skills.importSkill(c.page, await navigation.openSkills(c.page), args.filePath);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function skills_search(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 skills.search','skills.search',{channel:'dom',scope:'skills'},async()=>{const result=await skills.search(c.page, await navigation.openSkills(c.page), args.term);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function skills_listCards(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 skills.listCards','skills.listCards',{channel:'dom',scope:'skills'},async()=>{const result=await skills.listCards(await navigation.openSkills(c.page));return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function skills_readSwitch(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 skills.readSwitch','skills.readSwitch',{channel:'dom',scope:'skills'},async()=>{const result=await skills.readSwitch(c.page, await navigation.openSkills(c.page), args.term);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function skills_setSwitch(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 skills.setSwitch','skills.setSwitch',{channel:'dom',scope:'skills'},async()=>{const result=await skills.setSwitch(c.page, await navigation.openSkills(c.page), args.term, args.on);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
export async function skills_openAndReadDetail(ctx,args={}){const c=await connect(ctx);try{const read=await ctx.recorder.read('PC88 skills.openAndReadDetail','skills.openAndReadDetail',{channel:'dom',scope:'skills'},async()=>{const result=await skills.openAndReadDetail(c.page, await navigation.openSkills(c.page), args.term);return {value:result??null,raw:{parameters:args}};});return {observations:{read}};}finally{await c.close();}}
