import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=path.resolve(fileURLToPath(new URL('../',import.meta.url))),repo=path.resolve(root,'../..'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),jsonl=p=>fs.readFileSync(p,'utf8').trim().split(/\r?\n/).filter(Boolean).map(JSON.parse),cases=JSON.parse(fs.readFileSync(path.join(root,'用例/cases.json'),'utf8')),results=cases.map(c=>JSON.parse(fs.readFileSync(path.join(root,'结果',c.id+'.json'),'utf8'))),calls=jsonl(path.join(root,'运行日志/业务调用.jsonl')),readEvents=jsonl(path.join(root,'运行日志/business.jsonl')),byCall=new Map(calls.map(c=>[c.call_id,c])),byRead=new Map(readEvents.filter(e=>e.kind==='read').map(e=>[e.event_id,e])),issues=[],files=new Map();
for(const c of calls)for(const [p,h]of [[c.args_path,c.args_sha256],[c.return_path,c.return_sha256],...c.modules.map(m=>[m.snapshot,m.sha256])]){const absolute=path.resolve(root,p);files.set(absolute,h);if(!fs.existsSync(absolute)||sha(absolute)!==h)issues.push({call:c.call_id,file:p,error:'Hash mismatch'});}
for(const r of results){const assigned=cases.find(c=>c.id===r.case_id);for(const a of assigned.assertions){const x=r.assertions.find(x=>x.id===a.id);if(!x||x.actual==null)issues.push({case:r.case_id,assertion:a.id,error:'Not observed'});for(const ref of x?.read_refs||[]){const e=byRead.get(ref);if(!e||!r.business_call_refs.includes(e.business_call_id)||!byCall.has(e.business_call_id))issues.push({case:r.case_id,ref,error:'Read does not belong to case'});}}}
const bindings=JSON.parse(fs.readFileSync(path.join(root,'运行上下文.json'),'utf8'));const manifest=JSON.parse(fs.readFileSync(path.join(bindings.base,'夹具索引.json'),'utf8'));for(const f of manifest)if(sha(path.resolve(root,f.path))!==f.sha256)issues.push({fixture:f.path,error:'Hash mismatch'});
const totalAssertions=results.reduce((n,r)=>n+r.assertions.length,0),summary={cases:results.length,pass:results.filter(r=>r.status==='通过').length,fail:results.filter(r=>r.status==='失败').length,uncertain:results.filter(r=>r.status==='不确定').length,assertions:totalAssertions,observed:results.flatMap(r=>r.assertions).filter(a=>a.actual!=null).length,business_calls:calls.length,unique_functions:new Set(calls.map(c=>c.function_name)).size,checked_evidence_files:files.size,issues};fs.writeFileSync(path.join(root,'最终校验.json'),JSON.stringify(summary,null,2));
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);fs.writeFileSync(path.join(root,'代码索引.json'),JSON.stringify(walk(path.join(root,'code')).map(p=>({path:path.relative(root,p),sha256:sha(p)})),null,2));
const entries=[['application.readDetailIdentity','SM-05/08','原函数只返回详情全文，不能直接取得技术name、版本、来源'],['conversation.readCompletion','SM-03','原读取只数运行指示，不证明指定会话已完成'],['settings.listShortcuts','SM-10','不应猜中文快捷键行名，先读取实际行'],['conversation.readProjectControls','SM-02','区分可见项目控件与隐藏侧栏新会话按钮'],['conversation.readProjectOptions','SM-02','已有项目菜单只有项目名，不是完整路径']].map(([name,case_ids,gap])=>({function_name:name,case_ids:case_ids.split('/'),gap,file:JSON.parse(fs.readFileSync(path.join(repo,'tools/tpt-work/business/catalog.json'),'utf8')).functions.find(f=>f.name===name).file,promotion_status:'按用户授权已并入工具库，来源与本轮调用保留'}));fs.writeFileSync(path.join(root,'新增函数清单.json'),JSON.stringify(entries,null,2));
fs.writeFileSync(path.join(root,'报告.md'),`# 工具体系冒烟评估\n\n12条冒烟全部实际尝试，当前结果${summary.pass}通过、${summary.fail}失败、${summary.uncertain}不确定；${summary.observed}/${summary.assertions}条断言取得真实值。校验issues=${JSON.stringify(issues)}，检查${files.size}个证据文件哈希。所有产品操作都通过登记的业务函数。\n\n## 工具评估\n\n- 功能路径→plan→catalog可找到核心操作。详情字段、完成终态、快捷键实际行与项目控件发现原本不足，已补5个函数，并更新相关冒烟映射。\n- 项目菜单只显示名称：按唯一项目名选择并回读，不声称UI证明完整物理路径。项目控件按可见workspace定位，避免命中隐藏侧栏新会话按钮。\n- 助手正文可能与thinking同时含标记：主题函数改为精确正文匹配，并绑定session；已打开目标会话时直接回读身份，不强求侧栏重复进入。\n- 技能/专家输出请求未包含答案，多行输入和独立资源加载曾在函数验证阶段核验。开关按启用→停用→启用且每次重开验证。主题只对SM-03同一会话、同一精确正文比较前后及恢复颜色。\n- 首轮8通过、4不确定；修正配置、定位和调用方式后，只补测受影响场景及恢复。历史尝试保留，不能据首轮不确定给产品失败结论。\n\n## 限制与恢复\n\n这轮验证12条冒烟，没有实机重跑140条。171个函数的模块/参数/映射校验与12条冒烟通过分别报告，不声称全部171函数已逐一实机验证。\n\n本轮技能和前轮工具验证技能已停用并回读；主题恢复${bindings.theme_initial}；最终草稿无引用和附件，页面弹层关闭。本轮专家、技能、会话和夹具保留待审，不删除用户资产。前轮链接服务的PID检查与收尾另见函数库验证记录。\n\n## 后续执行\n\n140条任务已安排在../2026-10-06-函数体系全面回归/README.md，9批按共享场景组织；执行者必须保留新增函数，并在报告复盘是否并入库。管理者不执行这140条。\n`);console.log(JSON.stringify(summary,null,2));if(issues.length)process.exitCode=1;
