import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath,pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {catalog,validate} from '../call.mjs';
const root=path.resolve(fileURLToPath(new URL('../',import.meta.url))),issues=[],checked=[];
const directories=['automation','business'];const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
for(const p of directories.flatMap(d=>walk(path.join(root,d))).filter(p=>p.endsWith('.mjs'))){const r=spawnSync(process.execPath,['--check',p],{encoding:'utf8'});if(r.status!==0)issues.push({file:path.relative(root,p),error:r.stderr});}
for(const f of catalog.functions){try{const p=path.join(root,f.file),m=await import(pathToFileURL(p).href);if(typeof m[f.export]!=='function')throw Error('Export missing');checked.push({name:f.name,file:f.file,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),status:'module-load-verified'});}catch(e){issues.push({function:f.name,error:e.message});}}
const coverage=JSON.parse(fs.readFileSync(path.join(root,'coverage/cases.json'),'utf8'));
for(const c of coverage.cases){if(!c.calls.length)issues.push({case:c.case_id,error:'No calls mapped'});for(const call of [...c.calls,...c.corrections]){const f=catalog.functions.find(f=>f.name===call.name);if(!f){issues.push({case:c.case_id,error:'Unknown function '+call.name});continue;}if(call.args&&typeof call.args==='object')try{validate(f.parameters,call.args);}catch(e){issues.push({case:c.case_id,function:call.name,error:e.message});}}}
const result={captured_at:new Date().toISOString(),functions:checked.length,cases:coverage.total,scope:coverage.scope,issues,verification_levels:{module_load:'all registered exports',case_mapping:'140 regression history action/read mappings + 12 explicit smoke plans',live_ui:'see exploratory review task; not all cases rerun'},checked};
fs.writeFileSync(path.join(root,'verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({functions:checked.length,cases:coverage.total,issues},null,2));if(issues.length)process.exitCode=1;
