// Creates case documents only. Refuses to overwrite a started smoke run.
const fs=require('node:fs'),path=require('node:path');const root=path.resolve(__dirname,'..');
if(fs.existsSync(path.join(root,'运行')))throw Error('已有运行记录，不覆盖用例');
const rows=[
['SM-01',['应用','接入'],'连接真实产品',[],['访问本机CDP /json/version和/json/list，记录目标页面URL和包哈希','连接属于TPT Work的页面，读取当前可见主界面及登录状态'],[['目标为TPT页面','目标URL属于该实例且主界面可读，不把普通浏览器页面当产品',true]]],
['SM-02',['对话','创建与配置'],'新任务、已有项目和模型',['SM-01'],['进入新建任务，读取编辑器可见且可编辑状态','在选择项目中选择已存在项目；记录所选项目名，回读本任务项目控件','选择或确认标准/low；清理本次草稿中已有技能/专家引用，记录干净状态'],[['任务编辑器可用','读取本次编辑器isVisible及可编辑状态，两者都成立为true',true],['已选已有项目','读取任务项目控件文本，与选项中预先记录的project比较','$project'],['模型与推理等级','读取本次模型控件，规范化为标准/low','标准/low']]],
['SM-03',['对话','文本执行'],'标准/low完成短对话',['SM-02'],['向本次干净任务发送“只回复：<chat_reply>。不要使用工具。”；chat_reply来自预期.json','绑定发送后session及这一次助手消息，等待明确完成或模型等待上限','读取该助手最终纯文本及执行终态'],[['助手回复','读取本轮目标助手最终文本，仅去掉首尾空白，与chat_reply精确比较','$chat_reply'],['已完成','读取本轮完成终态，不以全页不存在运行文字替代',true]]],
['SM-04',['对话','附件'],'草稿附件添加与移除',['SM-02'],['进入新草稿，通过HTML文件input添加本轮smoke-note.txt，不发送','在当前草稿附件区读取文件名，再点击这一文件的移除控件','回读同一草稿附件区数量'],[['目标文件已添加','在当前草稿附件区读取smoke-note.txt是否存在',true],['移除后无附件','读取同一草稿附件区文件卡数量，目标区域定位失败为null',0]]],
['SM-05',['技能','导入与发现'],'新技能导入、搜索和详情',['SM-01'],['确认本轮skill_name尚未安装；用HTML input提交新SKILL.md导入','读取本次导入反馈，使用内部name搜索并定位唯一对象','打开这张卡片详情，读取内部name、版本和来源'],[['搜索命中目标','按本轮内部name识别搜索结果，不只数所有卡片，目标对象数量为1',1],['详情内部名','读取目标详情字段并按字段语义去引号，不能做宽松子串匹配','$skill_name'],['详情版本','读取该对象version','1.2.3'],['本地来源','读取该对象来源的规范类别，用户创建映射为用户','用户']]],
['SM-06',['技能','状态控制'],'技能开关可改变并保持',['SM-05'],['记录本轮技能初始状态，不假定默认启用或停用','启用该技能，离开列表再返回，读取同一对象checked','停用后同样重开读取；最后再次启用供下一条使用'],[['启用保存','重开后读取目标开关checked或aria-checked的真实布尔值',true],['停用保存','停用并重开后读取同一目标开关布尔值',false],['调用前已启用','最后启用后重新读取目标开关',true]]],
['SM-07',['技能','使用效果'],'选中技能并获得规则回复',['SM-06'],['建立干净任务，只选择本轮技能；使用入口是否复用会话另记录，本条不要求它创建新会话','读取实际选中技能chip身份，确认没有其他技能/专家引用','发送“请执行当前选中回归技能的固定回复规则，不使用工具。”，请求中不写目标回复','绑定本轮session，等完成后读取该助手最终回复'],[['选中技能身份','读取实际引用chip对应内部name，不在全页找名字','$skill_name'],['技能规则效果','读取本轮助手最终文本trim，与预期.json的skill_reply比较','$skill_reply']]],
['SM-08',['专家','导入与发现'],'新专家目录导入和详情',['SM-01'],['确认本轮expert_name尚未安装；用目录input提交生成的expert目录','读取导入反馈，定位该内部name对应专家，打开详情','读取详情内部name和版本'],[['专家身份','读取目标详情name并按字段语义规范，不用标题猜身份','$expert_name'],['专家版本','读取该专家详情version','1.2.3']]],
['SM-09',['专家','使用效果'],'选中专家并获得规则回复',['SM-08'],['建立干净任务，选择本轮专家，不选择额外技能；读取实际专家chip身份','发送“请执行当前选中回归专家的固定回复规则，不使用工具。”，请求中不写目标回复','绑定本轮session，等完成后读取该助手最终回复'],[['选中专家身份','实际引用对应本轮expert_name；若UI资源标识带agent-前缀，记录原值及明确映射后比较内部名','$expert_name'],['专家规则效果','读取本轮助手最终纯文本trim，比较expert_reply','$expert_reply']]],
['SM-10',['设置','入口'],'设置与快捷键面板可打开',['SM-01'],['通过头像菜单打开设置，确认常规内容可读','点击编辑快捷键；用关闭快捷键/修改新会话快捷键按钮定位独立快捷键dialog','读取新会话和搜索会话当前组合；关闭快捷键及设置，不改组合'],[['常规设置可读','在真实设置dialog读取权限、语言、外观字段标签，三者均存在为true',true],['快捷键内容可读','在独立快捷键dialog中读到新会话及搜索会话两条非空有效组合；记录具体组合，不预设CtrlN/K',true]]],
['SM-11',['设置','主题效果'],'主题改变并恢复',['SM-03','SM-10'],['保存设置中的外观初值；在SM-03会话助手正文记录computed color/background及影响它的实际容器','根据当前实际浅/深色选择相反的明确主题，保存并等待稳定；回读设置值及同一正文/容器的计算颜色','恢复原设置选项（可能是跟随系统），重开回读；在同一正文核验颜色恢复'],[['主题保存','回读外观选项，与切换前预先选择的theme_changed比较','$theme_changed'],['实际主题效果','比较同一正文/容器前后color/background，至少一个真实计算值变化为true',true],['主题选项恢复','重开读取恢复后的选项','$theme_initial'],['正文颜色恢复','同一目标恢复后的计算颜色与初始颜色一致，保留前后原值',true]]],
['SM-12',['收尾','恢复核验'],'样本停用与环境恢复',['SM-04','SM-07','SM-09','SM-11'],['将本轮导入技能停用并重开列表回读，不删除','确认本次附件草稿已无附件、设置和快捷键弹层关闭，主题仍为初值','在干净草稿解除本轮专家/技能引用并回读；保留导入样本和测试会话待审，记录所有残留'],[['样本技能已停用','重开列表读取本轮skill_name的开关',false],['主题最终恢复','最终独立回读设置外观选项','$theme_initial'],['没有未恢复操作','分别保存附件数、弹层状态、本次草稿引用、改动项恢复值；全部已恢复为true，任何未验证为null',true]]]
];
const cases=rows.map(([id,feature_path,title,depends_on,steps,assertions])=>({id,title,feature_path,depends_on,contract_version:'smoke-1.0',steps,wait:{ui_ms:5000,model_ms:90000,rule:'按明确目标状态等待；超时保存实际现场，允许一次有依据定位修正'},assertions:assertions.map(([target,read,expected],i)=>({id:id+'-A'+(i+1),target,read,operator:'equals',expected})),evidence:'实际动作/原始读取/对象身份/断言结果/代码版本；通过默认不截图',cleanup:'仅改本轮样本；临时设置恢复并回读；停用本轮技能，专家/会话保留待审'}));
if(cases.length!==12||new Set(cases.map(c=>c.id)).size!==12)throw Error('invalid queue');
fs.mkdirSync(path.join(root,'用例'),{recursive:true});fs.writeFileSync(path.join(root,'用例/cases.json'),JSON.stringify(cases,null,2)+'\n');
const lines=['# 冒烟用例','','预期中$字段来自本轮夹具预期或操作前真实读取，不从操作后actual倒填。按顺序共享场景执行；功能层级见每条路径。',''];for(const c of cases){lines.push(`## ${c.id} ${c.title}`,'',`功能：${c.feature_path.join(' → ')}；前置：${c.depends_on.join('、')||'已授权空闲实例及登录态'}。`,'',...c.steps.map((s,i)=>`${i+1}. ${s}。`),'','通过条件：','',...c.assertions.map(a=>`- ${a.id} ${a.target}：${a.read}；预期 ${JSON.stringify(a.expected)}。`),'');}fs.writeFileSync(path.join(root,'用例.md'),lines.join('\n'));
console.log(JSON.stringify({cases:cases.length,assertions:cases.reduce((n,c)=>n+c.assertions.length,0),model_requests:3,execution:'未执行'}));
