import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {invoke} from '../../../tools/tpt-work/call.mjs';
const root=path.resolve(fileURLToPath(new URL('../',import.meta.url))),env=JSON.parse(fs.readFileSync(path.join(root,'环境记录.json'),'utf8')),b=JSON.parse(fs.readFileSync(path.join(root,'运行上下文.json'),'utf8')),shared={},results=[];let refs=[],current;
const call=async(name,args={})=>{const r=await invoke(name,args,{taskRoot:root,environment:env,shared});refs.push(r.call_id);if(r.status==='error')throw Error(name+': '+r.error.message);return r.observations.observations;};
const check=(id,actual,expected,...read)=>({id,actual,expected,pass:actual!=null&&JSON.stringify(actual)===JSON.stringify(expected),read_refs:read.map(r=>r.event_id)});
async function test(id,fn){current=id;refs=[];const assertions=[];let error;try{await fn(assertions);}catch(e){error=e.message;}const p=path.join(root,'结果',id+'.json'),old=JSON.parse(fs.readFileSync(p,'utf8')),oldAttempt=old.attempt||'A01',attempt='A'+String(Number(oldAttempt.slice(1))+1).padStart(2,'0');for(const x of old.assertions)if(!assertions.some(a=>a.id===x.id))assertions.push({...x,actual:null,pass:false,reason:error});const result={...old,attempt,supersedes:'历史/'+id+'-'+oldAttempt+'.json',retest_reason:'项目控件按已观察的workspace定位；目标会话已打开时不强求侧栏再次选择',status:error||assertions.some(a=>a.actual===null)?'不确定':assertions.every(a=>a.pass)?'通过':'失败',assertions,business_call_refs:refs,error:error??null};fs.mkdirSync(path.join(root,'历史'),{recursive:true});fs.copyFileSync(p,path.join(root,'历史',id+'-'+oldAttempt+'.json'));fs.writeFileSync(p,JSON.stringify(result,null,2));results.push(result);console.log(JSON.stringify({case:id,status:result.status,error}));}
try{
await test('SM-02',async a=>{await call('smoke.navigation.closeSidebarPanels');const r=await call('conversation.newTask',{projectPath:env.project_path});await call('conversation.clearDraft');a.push(check('SM-02-A1',r.editor.value,true,r.editor),check('SM-02-A2',r.project.value,'tpt-workspace',r.project),check('SM-02-A3',r.model.value.join('/'),'标准/low',r.model));});
await test('SM-03',async a=>{const reply='SMOKE_CHAT_RETEST_'+b.run;const r=await call('conversation.sendMessage',{text:'只回复：'+reply+'。不要使用工具。',timeoutMs:45000});const composer=(await call('conversation.readComposer')).read;b.chat_reply=reply;b.sm03_session=composer.value.session;const completed=(await call('conversation.readCompletion',{sessionId:b.sm03_session,replyText:reply})).read;a.push(check('SM-03-A1',r.assistant.value,reply,r.assistant),check('SM-03-A2',completed.value.completed,true,completed));});
await test('SM-10',async a=>{const g=await call('settings.readGeneral'),r=(await call('settings.listShortcuts')).read;const creation=r.value.filter(x=>/新.*会话|新.*任务/.test(x.text)),search=r.value.filter(x=>/搜索.*会话|搜索.*任务/.test(x.text));a.push(check('SM-10-A1',!!g.theme.value&&!!g.permission.value&&!!g.language.value,true,g.theme,g.permission,g.language),check('SM-10-A2',creation.length===1&&search.length===1&&!!creation[0].binding&&!!search[0].binding,true,r));});
await test('SM-11',async a=>{await call('conversation.openSession',{sessionId:b.sm03_session,title:'SMOKE_CHAT_RETEST'});const before=(await call('settings.readConversationAppearance',{sessionId:b.sm03_session,replyText:b.chat_reply})).read,changed=before.value.bodyColor==='rgb(15, 17, 21)'?'深色':'浅色',saved=(await call('settings.setTheme',{value:changed})).after,after=(await call('settings.readConversationAppearance',{sessionId:b.sm03_session,replyText:b.chat_reply})).read;await call('settings.setTheme',{value:b.theme_initial});const theme=(await call('settings.readGeneral')).theme,last=(await call('settings.readConversationAppearance',{sessionId:b.sm03_session,replyText:b.chat_reply})).read;const colors=x=>[x.bodyColor,x.bodyBg,x.rootColor,x.rootBg];a.push(check('SM-11-A1',saved.value,changed,saved),check('SM-11-A2',JSON.stringify(colors(before.value))!==JSON.stringify(colors(after.value)),true,before,after),check('SM-11-A3',theme.value,b.theme_initial,theme),check('SM-11-A4',colors(last.value),colors(before.value),last,before));});
await test('SM-12',async a=>{for(const internalName of [b.skillName,'smoke-skill-tools-20261006-smoke'])await call('skills.setSkillEnabled',{displayName:'本轮快速回归技能',internalName,value:false});await call('smoke.skills.closeSkills');await call('smoke.skills.openSkills');const state=(await call('skills.readSkillCard',{displayName:'本轮快速回归技能',internalName:b.skillName})).switch;await call('smoke.navigation.closeSidebarPanels');await call('settings.setTheme',{value:b.theme_initial});const theme=(await call('settings.readGeneral')).theme;await call('conversation.newTask');await call('conversation.clearDraft');await call('conversation.closeDialogs');const d=(await call('conversation.readDialogs')).read,count=(await call('attachments.readDraftState')).count,composer=(await call('conversation.readComposer')).read;a.push(check('SM-12-A1',state.value,false,state),check('SM-12-A2',theme.value,b.theme_initial,theme),check('SM-12-A3',count.value===0&&d.value.length===0&&!composer.value.text,true,count,d,composer));});
}finally{await shared.connection?.close();fs.writeFileSync(path.join(root,'运行上下文.json'),JSON.stringify(b,null,2));fs.writeFileSync(path.join(root,'补测汇总.json'),JSON.stringify(results,null,2));}
