// 本任务调度与断言代码：产品操作全部通过已登记业务函数，禁止直接 Playwright 操作。
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {invoke,catalog} from '../../../tools/tpt-work/call.mjs';
const task=path.resolve(fileURLToPath(new URL('../',import.meta.url))),env=JSON.parse(fs.readFileSync(path.join(task,'环境记录.json'),'utf8')),cases=JSON.parse(fs.readFileSync(path.join(task,'用例/cases.json'),'utf8')),plans=JSON.parse(fs.readFileSync(new URL('../../../tools/tpt-work/coverage/cases.json',import.meta.url),'utf8')).cases;
const shared={},runtime={},run='tool-smoke-20261006-eval1',calls=[],results=[];let current;
const call=async(name,args={},expectedSession)=>{if(!catalog.functions.some(f=>f.name===name))throw Error('工具索引缺失 '+name);const r=await invoke(name,args,{taskRoot:task,environment:env,shared,runtime,expectedSession});calls.push({case_id:current,name,call_id:r.call_id,status:r.status});if(r.status==='error')throw Error(name+': '+r.error.message);return r.observations.observations;};
const check=(id,actual,expected,reads=[])=>({id,actual,expected,pass:actual!==null&&actual!==undefined&&JSON.stringify(actual)===JSON.stringify(expected),read_refs:reads.filter(Boolean).map(r=>r.event_id)});
async function test(id,fn){current=id;const start=calls.length,started=new Date().toISOString(),a=[];let error;try{await fn(a);}catch(e){error=e.message;}const definition=cases.find(c=>c.id===id);for(const x of definition.assertions)if(!a.some(r=>r.id===x.id))a.push({id:x.id,actual:null,expected:x.expected,pass:false,reason:error||'本轮未观测'});const used=calls.slice(start),plan=plans.find(p=>p.case_id===id),mapped=new Set([...plan.calls,...plan.corrections].map(c=>c.name));const result={case_id:id,started_at:started,ended_at:new Date().toISOString(),status:error||a.some(x=>x.actual===null)?'不确定':a.every(x=>x.pass)?'通过':'失败',assertions:a,business_call_refs:used.map(x=>x.call_id),tool_discovery:{feature_path:definition.feature_path,plan_functions:[...mapped],used:used.map(x=>x.name),additional_functions:used.map(x=>x.name).filter(n=>!mapped.has(n)),all_product_operations_via_functions:true},...(error?{error}:{})};results.push(result);fs.mkdirSync(path.join(task,'结果'),{recursive:true});fs.writeFileSync(path.join(task,'结果',id+'.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({case:id,status:result.status,error}));}
const bindings={run};let fixture,themeInitial,sm03session,initialAppearance;
try{
 current='SETUP';await call('smoke.navigation.closeSidebarPanels');
 fixture=(await call('fixtures.prepareSmokeFixtures',{run})).read.value;Object.assign(bindings,fixture);themeInitial=(await call('settings.readGeneral')).theme.value;bindings.theme_initial=themeInitial;fs.writeFileSync(path.join(task,'预期.json'),JSON.stringify(bindings,null,2));
 await test('SM-01',async a=>{const r=(await call('application.inspectConnection',{asarPath:env.asar_path})).read;a.push(check('SM-01-A1',r.value.url.startsWith('dsh-app://app/')&&r.value.mainReadable,true,[r]));});
 await test('SM-02',async a=>{const r=await call('conversation.newTask',{projectPath:env.project_path});await call('conversation.clearDraft');a.push(check('SM-02-A1',r.editor.value,true,[r.editor]),check('SM-02-A2',r.project.value,path.basename(env.project_path.replaceAll('\\','/')),[r.project]),check('SM-02-A3',r.model.value.join('/'),'标准/low',[r.model]));});
 await test('SM-03',async a=>{const reply='SMOKE_CHAT_'+run+'_OK';bindings.chat_reply=reply;const r=await call('conversation.sendMessage',{text:'只回复：'+reply+'。不要使用工具。',timeoutMs:45000});const composer=(await call('conversation.readComposer')).read;sm03session=composer.value.session;bindings.sm03_session=sm03session;const state=(await call('conversation.readCompletion',{sessionId:sm03session,replyText:reply})).read;a.push(check('SM-03-A1',r.assistant.value,reply,[r.assistant]),check('SM-03-A2',state.value.completed,true,[state]));});
 await test('SM-04',async a=>{await call('conversation.newTask');const p=path.join(fixture.base,'smoke-note.txt');await call('fixtures.writeFile',{path:p,content:'Harmless attachment '+run});const added=(await call('attachments.addLocalFiles',{paths:[p]})).names;await call('attachments.removeAttachment',{name:'smoke-note.txt'});const count=(await call('attachments.readDraftState')).count;a.push(check('SM-04-A1',added.value.includes('smoke-note.txt'),true,[added]),check('SM-04-A2',count.value,0,[count]));});
 await test('SM-05',async a=>{const names=(await call('skills.readListIdentity')).read;if(names.value.includes(fixture.skillName))throw Error('新样本身份已安装');await call('skills.importSingleFile',{filePath:path.join(fixture.base,'skill-src/SKILL.md'),displayName:'本轮快速回归技能',internalName:fixture.skillName});const search=(await call('skills.searchSkills',{term:fixture.skillName,internalName:fixture.skillName}));await call('skills.readSkillDetail',{displayName:'本轮快速回归技能',internalName:fixture.skillName});const r=(await call('application.readDetailIdentity',{kind:'skill'})).read;bindings.skill_identity=r.value;a.push(check('SM-05-A1',search.match?.value??search.count?.value??null,1,[search.match||search.count]),check('SM-05-A2',r.value.name,fixture.skillName,[r]),check('SM-05-A3',r.value.version,'1.2.3',[r]),check('SM-05-A4',r.value.sourceCategory,'用户',[r]));});
 await test('SM-06',async a=>{for(const [i,value]of [true,false,true].entries()){await call('skills.setSkillEnabled',{displayName:'本轮快速回归技能',internalName:fixture.skillName,value});await call('smoke.skills.closeSkills');await call('smoke.skills.openSkills');const r=await call('skills.readSkillCard',{displayName:'本轮快速回归技能',internalName:fixture.skillName});const obs=r.switch||r.enabled;a.push(check('SM-06-A'+(i+1),obs?.value??null,value,[obs]));}});
 await test('SM-07',async a=>{await call('conversation.newTask');const ref=(await call('skills.quickUse',{displayName:'本轮快速回归技能',internalName:fixture.skillName})).reference;const r=await call('skills.useSkillRequest',{text:'请执行当前选中回归技能的固定回复规则，不使用工具。',answer:fixture.skillReply,timeoutMs:45000});a.push(check('SM-07-A1',ref.value,fixture.skillName,[ref]),check('SM-07-A2',r.assistant.value,fixture.skillReply,[r.assistant]));});
 await test('SM-08',async a=>{await call('experts.importDirectory',{dirPath:path.join(fixture.base,'expert-src'),displayName:'本轮快速回归专家',internalName:fixture.expertName});await call('experts.readDetail',{displayName:'本轮快速回归专家',internalName:fixture.expertName});const r=(await call('application.readDetailIdentity',{kind:'expert'})).read;a.push(check('SM-08-A1',r.value.name,fixture.expertName,[r]),check('SM-08-A2',r.value.version,'1.2.3',[r]));});
 await test('SM-09',async a=>{const ref=(await call('experts.useExpert',{displayName:'本轮快速回归专家',internalName:fixture.expertName})).reference;const r=await call('experts.useExpertRequest',{text:'请执行当前选中回归专家的固定回复规则，不使用工具。',answer:fixture.expertReply,timeoutMs:45000});a.push(check('SM-09-A1',ref.value.replace(/^agent-/,''),fixture.expertName,[ref]),check('SM-09-A2',r.assistant.value,fixture.expertReply,[r.assistant]));});
 await test('SM-10',async a=>{const g=await call('settings.readGeneral'),n=(await call('settings.readShortcut',{label:'新建会话'})).read,k=(await call('settings.readShortcut',{label:'搜索会话'})).read;a.push(check('SM-10-A1',!!g.theme.value&&!!g.language.value&&!!g.permission.value,true,[g.theme,g.language,g.permission]),check('SM-10-A2',!!n.value&&!!k.value,true,[n,k]));});
 await test('SM-11',async a=>{await call('conversation.openSession',{sessionId:sm03session,title:'SMOKE_CHAT_'+run});initialAppearance=(await call('settings.readConversationAppearance',{sessionId:sm03session,replyText:bindings.chat_reply})).read;const changed=initialAppearance.value.bodyColor==='rgb(15, 17, 21)'?'深色':'浅色';const s=(await call('settings.setTheme',{value:changed})).after,d=(await call('settings.readConversationAppearance',{sessionId:sm03session,replyText:bindings.chat_reply})).read;await call('settings.setTheme',{value:themeInitial});const restored=(await call('settings.readGeneral')).theme,last=(await call('settings.readConversationAppearance',{sessionId:sm03session,replyText:bindings.chat_reply})).read;const colors=v=>[v.bodyColor,v.bodyBg,v.rootColor,v.rootBg];a.push(check('SM-11-A1',s.value,changed,[s]),check('SM-11-A2',JSON.stringify(colors(initialAppearance.value))!==JSON.stringify(colors(d.value)),true,[initialAppearance,d]),check('SM-11-A3',restored.value,themeInitial,[restored]),check('SM-11-A4',colors(last.value),colors(initialAppearance.value),[last,initialAppearance]));});
 await test('SM-12',async a=>{await call('skills.setSkillEnabled',{displayName:'本轮快速回归技能',internalName:fixture.skillName,value:false});await call('smoke.skills.closeSkills');await call('smoke.skills.openSkills');const state=await call('skills.readSkillCard',{displayName:'本轮快速回归技能',internalName:fixture.skillName});await call('smoke.navigation.closeSidebarPanels');await call('settings.setTheme',{value:themeInitial});const theme=(await call('settings.readGeneral')).theme;await call('conversation.newTask');await call('conversation.clearDraft');await call('conversation.closeDialogs');const d=(await call('conversation.readDialogs')).read,att=(await call('attachments.readDraftState')).count,composer=(await call('conversation.readComposer')).read;a.push(check('SM-12-A1',(state.switch||state.enabled)?.value??null,false,[state.switch||state.enabled]),check('SM-12-A2',theme.value,themeInitial,[theme]),check('SM-12-A3',att.value===0&&d.value.length===0&&!composer.value.text,true,[att,d,composer]));});
}finally{await shared.connection?.close();fs.writeFileSync(path.join(task,'运行上下文.json'),JSON.stringify(bindings,null,2));fs.writeFileSync(path.join(task,'执行汇总.json'),JSON.stringify({results,calls},null,2));}
