const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=x=>JSON.parse(fs.readFileSync(path.join(root,x),'utf8'));
const cases=read('\u7528\u4f8b/cases.json').concat(read('\u7528\u4f8b/extra-cases.json'));
const recdir=path.join(root,'\u6267\u884c\u8bb0\u5f55'),evdir=path.join(root,'\u8bc1\u636e');
const records=new Map(),pairs=new Set(),counts={};const issues=[];
for(const c of cases){const p=path.join(recdir,c.id+'.json');if(!fs.existsSync(p)){issues.push('missing record '+c.id);continue;}const r=JSON.parse(fs.readFileSync(p,'utf8'));records.set(c.id,r);counts[r.status]=(counts[r.status]||0)+1;for(const a of r.attempts||[])pairs.add(c.id+'\0'+a.attempt_id);}
const observations=new Map();for(const line of fs.readFileSync(path.join(root,'\u89c2\u5bdf\u8bb0\u5f55.jsonl'),'utf8').split(/\r?\n/).filter(Boolean)){const o=JSON.parse(line);if(observations.has(o.observation_id))issues.push('duplicate observation '+o.observation_id);observations.set(o.observation_id,o);}
const index=fs.readFileSync(path.join(evdir,'\u7d22\u5f15.jsonl'),'utf8').split(/\r?\n/).filter(Boolean).map(JSON.parse),paths=new Set();let orphan=0;
for(const [i,e] of index.entries()){if(paths.has(e.path))issues.push('duplicate evidence path '+e.path);paths.add(e.path);const p=path.resolve(root,e.path),rel=path.relative(evdir,p);if(rel.startsWith('..')||path.isAbsolute(rel)||!fs.existsSync(p)){issues.push('missing/outside evidence '+e.path);continue;}const h=crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');if(h!==e.sha256)issues.push('hash mismatch '+e.path);if(!pairs.has(e.case_id+'\0'+e.attempt_id)){orphan++;const o=observations.get(e.observation_id);if(!o||o.legacy_attempt_id!==e.attempt_id||!o.related_cases?.includes(e.case_id))issues.push('orphan not mapped to observation row '+(i+1));}}
let executed=0;for(const [id,r] of records){if((r.status||'').startsWith('\u5df2\u6267\u884c'))executed++;for(const a of r.attempts||[]){for(const p of a.evidence||[]){const e=index.find(x=>x.path===p);if(!e||e.case_id!==id||e.attempt_id!==a.attempt_id)issues.push('attempt evidence ownership '+id+'/'+a.attempt_id+'/'+p);}for(const cp of a.checkpoints||[])for(const p of cp.evidence||[]){const e=index.find(x=>x.path===p);if(!e||e.case_id!==id||e.attempt_id!==a.attempt_id)issues.push('checkpoint evidence ownership '+id+'/'+a.attempt_id+'/'+p);}}}
console.log(JSON.stringify({total:cases.length,executed,counts,index_rows:index.length,registered_attempt_pairs:pairs.size,orphan_rows:orphan,observations:observations.size,issues},null,2));process.exitCode=issues.length?1:0;
