const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium}=require(path.join(process.env.TEMP,'tpt-cdp/node_modules/playwright-core'));
const dir=path.join(__dirname,'复测');fs.mkdirSync(dir,{recursive:true});
async function snapshot(page){return {url:page.url(),frames:await Promise.all(page.frames().map(async f=>({url:f.url(),text:await f.locator('body').innerText(),buttons:await f.locator('button').evaluateAll(es=>es.filter(e=>e.offsetWidth).map(e=>({text:e.innerText,aria:e.getAttribute('aria-label')})))})))};}
(async()=>{const b=await chromium.connectOverCDP('http://127.0.0.1:9234');try{const p=b.contexts().flatMap(c=>c.pages()).find(p=>p.url()==='dsh-app://app/');if(!p)throw Error('target missing');p.setDefaultTimeout(6000);const mode=process.argv[2]||'inspect';let output;
if(mode==='inspect')output=await snapshot(p);
else if(mode==='settings'){await p.locator('[data-slot="settings.user"] button[aria-haspopup="menu"]').click();await p.getByRole('menuitem',{name:'设置',exact:true}).click();await p.getByRole('dialog').filter({hasText:'常规'}).waitFor();output=await snapshot(p);}
else if(mode==='settings-section'){const name=process.argv[3];const d=p.getByRole('dialog').filter({hasText:'常规'});await d.getByRole('button',{name,exact:true}).click();output=await snapshot(p);}
else if(mode==='controls'){output=await p.getByRole('dialog').filter({hasText:'常规'}).evaluate(d=>({text:d.innerText,controls:[...d.querySelectorAll('button,input,[role="switch"]')].filter(e=>e.offsetWidth).map(e=>({tag:e.tagName,role:e.getAttribute('role'),aria:e.getAttribute('aria-label'),checked:e.getAttribute('aria-checked'),value:e.value,text:e.innerText,outer:e.outerHTML.slice(0,700)}))}));}
else if(mode==='memory-inputs'){output=await p.getByRole('dialog').filter({hasText:'常规'}).locator('input[type="checkbox"]').evaluateAll(es=>es.map(e=>({checked:e.checked,parent:e.parentElement.outerHTML,ancestor:e.parentElement.parentElement.innerText})));}
else if(mode==='shortcut'){await p.getByRole('dialog').filter({hasText:'常规'}).getByRole('button',{name:'编辑快捷键',exact:true}).click();output=await p.getByRole('dialog').evaluateAll(ds=>ds.filter(d=>d.offsetWidth).map(d=>({text:d.innerText,buttons:[...d.querySelectorAll('button')].map(e=>({text:e.innerText,aria:e.getAttribute('aria-label')}))})));}
else if(mode==='close-shortcut'){await p.getByRole('button',{name:'关闭快捷键',exact:true}).click();output={closed:await p.getByRole('button',{name:'关闭快捷键',exact:true}).count()===0};}
else if(mode==='memory-save'){const events=[];const stamp=(action,data)=>{const e={time:new Date().toISOString(),action,...data};events.push(e);fs.appendFileSync(path.join(dir,'memory-actions.jsonl'),JSON.stringify(e)+'\n');};
 const dlg=()=>p.getByRole('dialog').filter({hasText:'常规'});
 const input=label=>dlg().locator('.tpt-cfg-row').filter({has:p.locator('.tpt-cfg-label').filter({hasText:label})}).locator('input[type="checkbox"]');
 const reopen=async()=>{await dlg().getByRole('button',{name:'关闭',exact:true}).click();await p.locator('[data-slot="settings.user"] button[aria-haspopup="menu"]').click();await p.getByRole('menuitem',{name:'设置',exact:true}).click();await dlg().getByRole('button',{name:'记忆与进化',exact:true}).click();};
 for(const label of ['启用记忆','启用沉淀']){const before=await input(label).isChecked();stamp('before',{label,checked:before});try{await input(label).setChecked(!before);stamp('immediate',{label,checked:await input(label).isChecked(),target:!before});await p.waitForTimeout(1500);stamp('changed',{label,checked:await input(label).isChecked(),text:await dlg().innerText()});await reopen();stamp('reopened',{label,checked:await input(label).isChecked()});}finally{if(await input(label).isChecked()!==before)await input(label).setChecked(before);await p.waitForTimeout(700);await reopen();stamp('restored',{label,checked:await input(label).isChecked(),expected:before});}}output=events;}
else if(mode==='new-draft'){await p.getByRole('dialog').filter({hasText:'常规'}).getByRole('button',{name:'关闭',exact:true}).click();await p.getByRole('button',{name:'新建任务',exact:true}).click();await p.locator('[contenteditable="true"]').waitFor();output=await p.evaluate(()=>({text:document.body.innerText.slice(-2500),editors:[...document.querySelectorAll('[contenteditable="true"]')].map(e=>({text:e.innerText,outer:e.parentElement.outerHTML.slice(0,3000)})),buttons:[...document.querySelectorAll('button')].filter(e=>e.offsetWidth).slice(-25).map(e=>({text:e.innerText,aria:e.getAttribute('aria-label')}))}));}
else if(mode==='restore-view'){await p.getByRole('dialog').filter({hasText:'常规'}).getByRole('button',{name:'关闭',exact:true}).click();await p.getByRole('button',{name:'技能',exact:true}).click();await p.frames().find(f=>f.url().includes('/supcon-skills/ui')).getByRole('button',{name:'导入技能',exact:true}).waitFor();output={settings_closed:await p.getByRole('dialog').count()===0,skills_visible:await p.frames().find(f=>f.url().includes('/supcon-skills/ui')).getByRole('button',{name:'导入技能',exact:true}).isVisible()};}
else throw Error('unknown mode');
const file=mode+'-'+Date.now()+'.json';const obj={time:new Date().toISOString(),mode,output};fs.writeFileSync(path.join(dir,file),JSON.stringify(obj,null,2)+'\n');console.log(JSON.stringify({file,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,file))).digest('hex'),output}));
}finally{await b.close();}})().catch(e=>{fs.appendFileSync(path.join(dir,'errors.jsonl'),JSON.stringify({time:new Date().toISOString(),error:e.stack})+'\n');console.error(e.stack);process.exitCode=1;});
